/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_udc_gac_jhwloc_HwlocEnumTypes_HwlocCPUBindFlags */

#ifndef _Included_es_udc_gac_jhwloc_HwlocEnumTypes_HwlocCPUBindFlags
#define _Included_es_udc_gac_jhwloc_HwlocEnumTypes_HwlocCPUBindFlags
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
