/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_udc_gac_jhwloc_HwlocEnumTypes_HwlocObjectCacheType */

#ifndef _Included_es_udc_gac_jhwloc_HwlocEnumTypes_HwlocObjectCacheType
#define _Included_es_udc_gac_jhwloc_HwlocEnumTypes_HwlocObjectCacheType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
