/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_udc_gac_jhwloc_HWLOC */

#ifndef _Included_es_udc_gac_jhwloc_HWLOC
#define _Included_es_udc_gac_jhwloc_HWLOC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_udc_gac_jhwloc_HWLOC
 * Method:    jhwloc_get_api_version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_udc_gac_jhwloc_HWLOC_jhwloc_1get_1api_1version
  (JNIEnv *, jclass);

/*
 * Class:     es_udc_gac_jhwloc_HWLOC
 * Method:    jhwloc_api_version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_udc_gac_jhwloc_HWLOC_jhwloc_1api_1version
  (JNIEnv *, jclass);

/*
 * Class:     es_udc_gac_jhwloc_HWLOC
 * Method:    jhwloc_compare_types
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_es_udc_gac_jhwloc_HWLOC_jhwloc_1compare_1types
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
