/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_udc_gac_jhwloc_HwlocObject */

#ifndef _Included_es_udc_gac_jhwloc_HwlocObject
#define _Included_es_udc_gac_jhwloc_HwlocObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_udc_gac_jhwloc_HwlocObject
 * Method:    jhwloc_obj_type_string
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_udc_gac_jhwloc_HwlocObject_jhwloc_1obj_1type_1string
  (JNIEnv *, jobject, jint);

/*
 * Class:     es_udc_gac_jhwloc_HwlocObject
 * Method:    jhwloc_obj_type_is_normal
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_es_udc_gac_jhwloc_HwlocObject_jhwloc_1obj_1type_1is_1normal
  (JNIEnv *, jobject, jint);

/*
 * Class:     es_udc_gac_jhwloc_HwlocObject
 * Method:    jhwloc_obj_type_is_io
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_es_udc_gac_jhwloc_HwlocObject_jhwloc_1obj_1type_1is_1io
  (JNIEnv *, jobject, jint);

/*
 * Class:     es_udc_gac_jhwloc_HwlocObject
 * Method:    jhwloc_obj_type_is_memory
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_es_udc_gac_jhwloc_HwlocObject_jhwloc_1obj_1type_1is_1memory
  (JNIEnv *, jobject, jint);

/*
 * Class:     es_udc_gac_jhwloc_HwlocObject
 * Method:    jhwloc_obj_type_is_cache
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_es_udc_gac_jhwloc_HwlocObject_jhwloc_1obj_1type_1is_1cache
  (JNIEnv *, jobject, jint);

/*
 * Class:     es_udc_gac_jhwloc_HwlocObject
 * Method:    jhwloc_obj_type_is_dcache
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_es_udc_gac_jhwloc_HwlocObject_jhwloc_1obj_1type_1is_1dcache
  (JNIEnv *, jobject, jint);

/*
 * Class:     es_udc_gac_jhwloc_HwlocObject
 * Method:    jhwloc_obj_type_is_icache
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_es_udc_gac_jhwloc_HwlocObject_jhwloc_1obj_1type_1is_1icache
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
